import Head from 'next/head'
import Image from 'next/image'
import Style from '@/styles/Home.module.css'
import { Container, Row, Col } from 'react-bootstrap'
import Cookies from "js-cookie";
import { useEffect, useState } from 'react';
import axios from 'axios';
import { BASE_URL } from '@/utils/api';
import MemberSkeleton from '@/components/loader/MemberSkeleton';
import HomeSkeleton from '@/components/loader/HomeSkeleton';


 
// async function getData () {
//   let res = await axios.get(BASE_URL + '/duclub/api/homepage')
//   let data = await res.json()
//   console.log(data)
//   return data
//  }


  

export default function  Home() {
  const [data, setData] = useState('')
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

 


  useEffect(() => {
    const fetchData = async () => {
      try {
        setLoading(true); // Set loading to true before fetching
  
        const response = await axios.get(BASE_URL + `/duclub/api/homepage`);
        console.log(response.data)
  
        // Assuming the response.data has a property named 'room'
        setData(response?.data?.data);
      } catch (error) {
        console.error("Error fetching data:", error);
      } finally {
        setLoading(false); // Set loading to false after fetching, whether successful or not
      }
    };
  
    fetchData();
  }, []);





  return (
    <>
      <Head>
        <title>Dhaka University Club</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className={`${Style.home} pt-5`}>
        

        {
          loading ? (
            <HomeSkeleton></HomeSkeleton>
          ) :
          (
            <Container>
          <Row>
            <Col md={5} sm={12} className="mx-auto">
              <div className="d-flex">
                <Image src="/favicon.png" width={150} height={150} alt="du logo" />
                <div className="d-flex flex-column justify-content-center ms-2">
                  <h3>Dhaka University Club</h3>
                  <h3>ঢাকা বিশ্ববিদ্যালয় ক্লাব</h3>
                </div>
              </div>
            </Col>
            <Col md={12} className="mt-4">
              <h5 className={Style.title}>{data?.desig}</h5>

              {/* <p className={Style.des}> 
                 {data?.text}
              </p>
              <br /> */}

              <p dangerouslySetInnerHTML={{ __html: data?.text}} />
              
            </Col>
          </Row>
        </Container>
          )
        }
      </main>
    </>
  )
}
